#!/bin/bash
# /etc/init.d/rfid

### BEGIN INIT INFO
# Provides:          rfid
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Read RFID cards to control Volumio
# Description:       Source code at https://code.schettler.net/olav/volumio-rfid
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting rfid"
    # run application you want to start
    cd ~volumio/rfid
    ./cont.py
    ;;
  stop)
    echo "Stopping noip"
    # kill application you want to stop
    killall cont.py
    ;;
  *)
    echo "Usage: /etc/init.d/rfid {start|stop}"
    exit 1
    ;;
esac

exit 0
